"""
LangGraph / Custom Agent Middleware Integration Example
Demonstrates how `GovernanceRuntime` hooks into LangGraph nodes and agent loops:
  - pre_node_hook: Ingress prompt injection scanning & tool allowlist validation
  - post_node_hook: PII output sanitization & Atlas Merkle-DAG decision logging
  - human_checkpoint_hook: State-bound cryptographic human approval over paused_state_hash
"""

import sys
import time
from typing import Dict, Any, Tuple
from cryptography.hazmat.primitives.asymmetric import ed25519

# Ensure UTF-8 output formatting for Windows console compatibility
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

from agentic_gov.middleware import GovernanceRuntime
from agentic_gov.governance.themis import CheckpointStatus


def simulate_langgraph_workflow():
    print("==================================================================")
    print("Initializing Agentic Security & Governance Runtime Engine...")
    print("==================================================================")

    # 1. Initialize Governance Engine & Register Agent Identity
    runtime = GovernanceRuntime(allowed_tools={"SearxNGTool", "FinancialDatabaseTool"}, enable_layer2=False)
    agent_id, agent_identity = runtime.register_agent(name="LangGraphFinanceAgent", roles=["financial_analyst"])

    print(f"[SUCCESS] Agent Registered: ID='{agent_id}'")

    # ------------------------------------------------------------------
    # Pre-Node Hook (Input Scanning & Tool Intent Gate)
    # ------------------------------------------------------------------
    print("\n--- 1. Pre-Node Hook: Ingress Prompt Scanning ---")
    user_prompt = "Summarize revenue report for Q3 and query FinancialDatabaseTool"
    is_safe, receipt, clean_prompt = runtime.inspect_input(user_prompt, stage="INPUT")

    if not is_safe:
        print(f"[BLOCKED] Security Interceptor Blocked Prompt: {receipt.reason}")
        return
    print(f"[SAFE] Input Prompt Safe. Clean Payload: '{clean_prompt}'")

    # Validate Tool Dispatch
    print("\n--- 2. Tool Intent & Allowlist Validation ---")
    is_tool_allowed, tool_receipt = runtime.validate_tool(
        agent_id=agent_id,
        tool_name="FinancialDatabaseTool",
        query="SELECT * FROM q3_revenue_stats"
    )
    if not is_tool_allowed:
        print(f"[BLOCKED] Tool Gate Blocked Execution: {tool_receipt.reason}")
        return
    print("[SUCCESS] Tool Call Validated successfully (Action, Target, Scope approved).")

    # ------------------------------------------------------------------
    # Post-Node Hook (Output Sanitization & Merkle-DAG Logging)
    # ------------------------------------------------------------------
    print("\n--- 3. Post-Node Hook: Output Sanitization & Merkle-DAG Recording ---")
    raw_model_output = "Report generated by support@company.com using API key sk-99887766554433221100."
    sanitized_output, redaction_receipt = runtime.sanitize_output(raw_model_output)

    print(f"  Raw Output: '{raw_model_output}'")
    print(f"  Sanitized Output: '{sanitized_output}'")

    # Record Decision Node in Atlas Merkle-DAG
    action_node = runtime.record_decision_node(
        agent_identity=agent_identity,
        input_payload={"prompt": user_prompt},
        decision_payload={"output": sanitized_output},
        rules_applied=["rule_asi04_redaction@v1", "rule_sec01@v1"]
    )

    print(f"[MERKLE_DAG] Node Recorded: ID='{action_node.action_id}' | Node Hash='{action_node.node_hash[:16]}...'")

    # ------------------------------------------------------------------
    # Human Checkpoint Hook (Themis State-Bound Halting)
    # ------------------------------------------------------------------
    print("\n--- 4. Human-in-the-Loop Checkpoint (Themis Engine) ---")
    execution_state = {"action": "EXECUTE_LARGE_TRANSFER", "amount_usd": 150000.0, "target_account": "ACC_9941"}

    # Pause workflow and compute paused_state_hash
    checkpoint_id, paused_state_hash = runtime.themis.create_checkpoint(
        session_id="sess_langgraph_101",
        execution_state=execution_state
    )
    print(f"[THEMIS_PAUSE] Workflow Halting -> PENDING_HUMAN. Checkpoint ID: '{checkpoint_id}'")
    print(f"  State Hash Snapshot: '{paused_state_hash}'")

    # Register reviewer identity
    reviewer_key = ed25519.Ed25519PrivateKey.generate()
    reviewer_id = "compliance_officer_sarah"
    runtime.themis.register_reviewer(reviewer_id, reviewer_key.public_key())

    # Sign the exact paused_state_hash
    signature_hex = reviewer_key.sign(paused_state_hash.encode('utf-8')).hex()

    time.sleep(0.05)  # Simulate review dwell time

    # Submit Human Approval
    status, checkpoint_receipt, metadata = runtime.themis.submit_approval(
        checkpoint_id=checkpoint_id,
        reviewer_id=reviewer_id,
        current_execution_state=execution_state,
        signature_hex=signature_hex
    )

    if status == CheckpointStatus.APPROVED:
        print(f"[THEMIS_APPROVED] Human Checkpoint APPROVED by '{reviewer_id}'. Signature Validated!")
        print(f"  Review Dwell Time: {metadata['dwell_time_ms']:.2f}ms")
    else:
        print(f"[CHECKPOINT_STATUS] {status}")

    print("\n==================================================================")
    print("LangGraph / Custom Agent Middleware Workflow Completed Successfully!")
    print("==================================================================")


if __name__ == "__main__":
    simulate_langgraph_workflow()
